# Generated by Django 5.0.6 on 2024-07-10 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                limit_choices_to={"is_player": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
