# Generated by Django 5.0.6 on 2024-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0002_alter_playerstats_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_primary_position",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
