# Generated by Django 5.0.6 on 2024-07-20 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0004_customuser_created_at_team_manager_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstats",
            name="long_pass_fail",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="long_pass_success",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="short_pass_fail",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="short_pass_success",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="number_of_goals",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="number_of_loses",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="number_of_matches_played",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="number_of_wins",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="possession",
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_concided_goals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_goals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_outcome",
            field=models.CharField(
                choices=[("win", "Win"), ("draw", "Draw"), ("loss", "Loss")],
                default="draw",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_possession",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="opposing_team_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="players",
            field=models.ManyToManyField(
                related_name="team_stats_players", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="total_number_of_draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="total_number_of_goals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="total_number_of_loses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="total_number_of_matches_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="total_number_of_wins",
            field=models.IntegerField(default=0),
        ),
    ]
