# Generated by Django 5.0.6 on 2024-08-20 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0005_remove_playerstats_long_pass_fail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
