# Generated by Django 5.0.6 on 2024-08-22 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0006_alter_customuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_player",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscribed",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_height",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_primary_position",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_team",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_draws",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_goals",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_loses",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_matches_played",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_passes",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="total_number_of_wins",
        ),
        migrations.AddField(
            model_name="playerstats",
            name="goal_scored_time",
            field=models.JSONField(
                default=list, help_text="List of times when goals were scored"
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_goal_concided_time",
            field=models.JSONField(
                default=list,
                help_text="List of times when goals were conceded during the match",
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="match_goal_scored_time",
            field=models.JSONField(
                default=list,
                help_text="List of times when goals were scored during the match",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="current_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_team_stats",
                to="football_app.team",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="previous_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_team_stats",
                to="football_app.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamstats",
            name="match_outcome",
            field=models.CharField(
                choices=[("win", "Win"), ("draw", "Draw"), ("loss", "Loss")],
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("country", models.CharField(max_length=128)),
                ("founded_year", models.IntegerField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="league_logos/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="leagues", to="football_app.team"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams_list",
                to="football_app.league",
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_stats",
                to="football_app.league",
            ),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_date", models.DateTimeField()),
                ("venue", models.CharField(max_length=255)),
                ("home_team_score", models.IntegerField(blank=True, null=True)),
                ("away_team_score", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="scheduled", max_length=20)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("league", "League"),
                            ("knockout", "Knockout"),
                            ("friendly", "Friendly"),
                            ("group_stage", "Group_stage"),
                            ("semi_final", "Semi_final"),
                            ("quater_final", "Quater_final"),
                            ("final", "Final"),
                        ],
                        default="league",
                        max_length=20,
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="football_app.team",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="football_app.team",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="football_app.league",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="match_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="football_app.match",
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("height", models.FloatField(help_text="Height in meters")),
                ("age", models.IntegerField()),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=False)),
                (
                    "player_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_images/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="football_app.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="football_app.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="football_app.player",
            ),
        ),
        migrations.AlterField(
            model_name="teamstats",
            name="players",
            field=models.ManyToManyField(
                related_name="team_stats", to="football_app.player"
            ),
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="football_app.league",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="football_app.season",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="season_played",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="football_app.season",
            ),
        ),
        migrations.AlterField(
            model_name="teamstats",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_stats",
                to="football_app.season",
            ),
        ),
    ]
