# Generated by Django 5.0.6 on 2024-08-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0007_remove_customuser_is_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="leagues", to="football_app.team"
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="season_played",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="football_app.season",
            ),
        ),
    ]
