# Generated by Django 5.1.1 on 2024-09-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0008_alter_league_teams_alter_playerstats_season_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="id",
            new_name="user_id",
        ),
    ]
