# Generated by Django 5.1.1 on 2024-09-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0009_rename_id_customuser_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="age",
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
